/*
 * This file has been automatically generated by cffi-grovel.
 * Do not edit it by hand.
 */

#include <sys/utsname.h>

#include <stdio.h>
#include <stdlib.h>

#ifndef offsetof
#define offsetof(type, slot) ((int) ((char *) &(((type *) 0)->slot)))
#endif
#define sizeofslot(type, slot) (sizeof(((type *) 0)->slot))
#define stringify(x) #x
#define indirect_stringify(x) stringify(x)

#define SIGNEDP(x) (((x)-1)<0)
#define SIGNED_(x) (SIGNEDP(x)?"":"un")

void type_name(FILE *output, int signed_p, int size);

int main(int argc, char**argv) {
  FILE *output = argc > 1 ? fopen(argv[1], "w") : stdout;
  fprintf(output, ";;;; This file has been automatically generated by "
                  "cffi-grovel.\n;;;; Do not edit it by hand.\n\n");
  fprintf(output, "(cl:in-package #:TRIVIAL-FEATURES-TESTS)\n\n");

  /* cstruct section for UTSNAME */
  fprintf(output, "(cffi:defcstruct (");
  fprintf(output, "utsname");
  fprintf(output, " :size %i)", sizeof(struct utsname));
  fprintf(output, "\n  (");
  fprintf(output, "sysname");
  fprintf(output, " ");
  fprintf(output, ":char");
  fprintf(output, " :offset %i)", offsetof(struct utsname, sysname));
  fprintf(output, "\n  (");
  fprintf(output, "nodename");
  fprintf(output, " ");
  fprintf(output, ":char");
  fprintf(output, " :offset %i)", offsetof(struct utsname, nodename));
  fprintf(output, "\n  (");
  fprintf(output, "release");
  fprintf(output, " ");
  fprintf(output, ":char");
  fprintf(output, " :offset %i)", offsetof(struct utsname, release));
  fprintf(output, "\n  (");
  fprintf(output, "version");
  fprintf(output, " ");
  fprintf(output, ":char");
  fprintf(output, " :offset %i)", offsetof(struct utsname, version));
  fprintf(output, "\n  (");
  fprintf(output, "machine");
  fprintf(output, " ");
  fprintf(output, ":char");
  fprintf(output, " :offset %i)", offsetof(struct utsname, machine));
  fprintf(output, ")\n");
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "size-of-utsname");
  fprintf(output, " (cffi:foreign-type-size '");
  fprintf(output, "utsname");
  fprintf(output, "))\n");

  if  (output != stdout)
    fclose(output);
  return 0;
}

void type_name(FILE *output, int signed_p, int size) {
  if (signed_p) {
    switch (size) {
    case 1: fprintf(output, ":int8"); break;
    case 2: fprintf(output, ":int16"); break;
    case 4: fprintf(output, ":int32"); break;
    case 8: fprintf(output, ":int64"); break;
    default: goto error;
    }
  } else {
    switch(size) {
    case 1: fprintf(output, ":uint8"); break;
    case 2: fprintf(output, ":uint16"); break;
    case 4: fprintf(output, ":uint32"); break;
    case 8: fprintf(output, ":uint64"); break;
    default: goto error;
    }
  }

  return;

error:
  fprintf(output, "(cl:error \"No type of size ~D.\" %i)\n", size);
}
