;;;; This file has been automatically generated by cffi-grovel.
;;;; Do not edit it by hand.

(cl:in-package #:TRIVIAL-FEATURES-TESTS)

(cffi:defcstruct (utsname :size 1280)
  (sysname :char :offset 0)
  (nodename :char :offset 256)
  (release :char :offset 512)
  (version :char :offset 768)
  (machine :char :offset 1024))
(cl:defconstant size-of-utsname (cffi:foreign-type-size 'utsname))
